language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- pytest
notifications:
  slack:
    secure: e2PmfHLfjsJFXzDcBCImkjbW0NqcrDAdHRcXwvrretIzasW1ZnC6Bto1kT0mhVEiPWzyBcUdHqji6zG5D3x/Cs9HVrwdkCfSjawC7H7eZBBdYV5w9JFJGLkZTumrT6xhfpEsndRe/oX6VKYGmfDBu8NxfL4hzNRNQtDQkh4a1ruNg5QZTz2xyq37pcb4rnGtp4WNBNyo48z76AkCW5sKxitoa2zhbqtYbqbAzpOP7Qf2TAXYh+AkIlim9IC63+GC96WVZyl65JqnJORRiGnGmM75E59UZ58wiGiDgWXqteA+6nLTC6+P6P50cVLnObXfda+M3URJ+aRwTkhkPm7OLrVOUncILZm0RSrYLC2ZN1QW8XOwCKwSmdOFKfwvh2wdgffCtD2gVDGLIUr74siEqMAER/K9L4Z3S0/SqT56B+fvazRJT9L6ClWz6TVpGuDZvuX2c+fEGJm7tc5MqopWoiBsAPzuj21eq9XcFmj6nRc/PKC5wCgWncQaY0pA4rSjTYfWMse+ZeFWq9G7NO/tR6nCDUhx7ks2AhiJrXX8ce0ZQ8a51CU9gbVhTWuqZ6zwL7KGaQirqvoBW9q2xu98TVOJ6bIx4mVk9fZEcDk1z7uwtaOmK8lDgpiQASAMYW9JY7VB0M1pWJcvef4iqwZoC6Pw2CoU3BodVDqMaZ3hxPY=
deploy:
  provider: pypi
  user: InbarRose
  password:
    secure: hPfSAstmCUqQM0R64ml9s7QfJ/Void1eAGISIrmwUTnL6mu7Bcpt3bVVqGrsNG1+jTkRyxyvxsPYKIw30+E7OAkfzskEafRFYgiCjwvhxM1N6k/0kiF+WCauqOLXtBjTXZQShBzeb7iEsL0yLLvuPi2DdqXalTyKZZ81PgU2NORGLBl/+G4TTQk5nt+58SQjP1QvCVjGqIL3bChp2F2oos/SDBBnNAG6VU0ow7qcCQzT3yXnBwRMNFTgxlvYfWGqK+gy+qFyP1wwdtCYPlubsHCqznHY83Gx5w3rK1o2/59IBk3Xt4yLdR1Q+u29avwNTcnHMMSBtPdlBZE6uIpMV2I03paemb+b/WPUNwuw78hZwn5ULCdnuF51RKmqmUP92x18Rs9rAECU0qKE3el/x+wWBZBk2Vqgf4aKe6WQdJwymfEeRUSfRwYr4j/OYC/41sODEDQpwxRIYuy6LqlKlUn/fuYk/RkAYJx3IDtcM/acRtbBN9/wWR46M8mN5WvE28Y7waId19anUhZZ1TRFI88vrXGSLqDrCZmMSFStboioQ6EFXlTu3iOP8LHHLr5fS5+laj8fpw/lQtT3NWQg9VBpxPI2F5jJWCh6dO7iuyN6HDHwKMdzy8pf0hXITkDU5RGHZStCthhuSJsvC8C3mUtdsetsmfkxr1DOg/6XCOc=
