language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- pytest
notifications:
  slack:
    secure: e2PmfHLfjsJFXzDcBCImkjbW0NqcrDAdHRcXwvrretIzasW1ZnC6Bto1kT0mhVEiPWzyBcUdHqji6zG5D3x/Cs9HVrwdkCfSjawC7H7eZBBdYV5w9JFJGLkZTumrT6xhfpEsndRe/oX6VKYGmfDBu8NxfL4hzNRNQtDQkh4a1ruNg5QZTz2xyq37pcb4rnGtp4WNBNyo48z76AkCW5sKxitoa2zhbqtYbqbAzpOP7Qf2TAXYh+AkIlim9IC63+GC96WVZyl65JqnJORRiGnGmM75E59UZ58wiGiDgWXqteA+6nLTC6+P6P50cVLnObXfda+M3URJ+aRwTkhkPm7OLrVOUncILZm0RSrYLC2ZN1QW8XOwCKwSmdOFKfwvh2wdgffCtD2gVDGLIUr74siEqMAER/K9L4Z3S0/SqT56B+fvazRJT9L6ClWz6TVpGuDZvuX2c+fEGJm7tc5MqopWoiBsAPzuj21eq9XcFmj6nRc/PKC5wCgWncQaY0pA4rSjTYfWMse+ZeFWq9G7NO/tR6nCDUhx7ks2AhiJrXX8ce0ZQ8a51CU9gbVhTWuqZ6zwL7KGaQirqvoBW9q2xu98TVOJ6bIx4mVk9fZEcDk1z7uwtaOmK8lDgpiQASAMYW9JY7VB0M1pWJcvef4iqwZoC6Pw2CoU3BodVDqMaZ3hxPY=
deploy:
  provider: pypi
  user: InbarRose
  password:
    secure: k5fkz54Puur+6wd4w3pEAoL953bgAFCeVcRFCyPFUckCX5Wqw5MtO8knySRRmeQmTyqHWfq2AlJ5CPUayKeY0yLOowwoi/5ps4U0CD65/xu/pTNUyEB2WA0HyD0X8iWCphk0SETB6wgRd5bXY3owTbxr2HPopMFhXckZNY/DQDodQM0x+NnLZQYJtzWc5YHyehH5jV6GrC1z14Y6/65vAe00GBnjuNIa3T0n/ijnABV2sB83hxnLklbQHjiDlHbPtHrmwvs0KbqdBy+GC9HuHsG3p1H+jET0XQpVpk/hhxkV8qshPd6wO4R//NkMm2yeBnI8byIfv/NfiucNr4mFb7mPKNJxSFDkcBZullCdUr3aDo5SCqk9v0Wl3DwFXcYxgWpobRXF9okRG5jC4LiNyHeoq2Y9LKt8Nl3ISxul0ZsT8v/7MKcsev9UvSUISUOzO3YDCqBHcat7MIk5wGVZxAzYS4aoQKFB3mm6eLhnih4msmbppA+dkEPv+8hj9k1FxJA6bnAdvMMOwK9c7d5cZGfOZnGhD0g+gj2Q+mE1+u6Pql5ogpOtSqvHtZ71+MFkzJX7DteiEVuQ007LCvhjW0Q0GdbAWbSXg4qhEUhNRV1yNILmVv9alZYNZm0NinAuJowp9Lyw01mcCNlqIrbiF+4gVKfbZI7T9QPUUJB54gs=
