language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- pytest
notifications:
  slack:
    secure: e2PmfHLfjsJFXzDcBCImkjbW0NqcrDAdHRcXwvrretIzasW1ZnC6Bto1kT0mhVEiPWzyBcUdHqji6zG5D3x/Cs9HVrwdkCfSjawC7H7eZBBdYV5w9JFJGLkZTumrT6xhfpEsndRe/oX6VKYGmfDBu8NxfL4hzNRNQtDQkh4a1ruNg5QZTz2xyq37pcb4rnGtp4WNBNyo48z76AkCW5sKxitoa2zhbqtYbqbAzpOP7Qf2TAXYh+AkIlim9IC63+GC96WVZyl65JqnJORRiGnGmM75E59UZ58wiGiDgWXqteA+6nLTC6+P6P50cVLnObXfda+M3URJ+aRwTkhkPm7OLrVOUncILZm0RSrYLC2ZN1QW8XOwCKwSmdOFKfwvh2wdgffCtD2gVDGLIUr74siEqMAER/K9L4Z3S0/SqT56B+fvazRJT9L6ClWz6TVpGuDZvuX2c+fEGJm7tc5MqopWoiBsAPzuj21eq9XcFmj6nRc/PKC5wCgWncQaY0pA4rSjTYfWMse+ZeFWq9G7NO/tR6nCDUhx7ks2AhiJrXX8ce0ZQ8a51CU9gbVhTWuqZ6zwL7KGaQirqvoBW9q2xu98TVOJ6bIx4mVk9fZEcDk1z7uwtaOmK8lDgpiQASAMYW9JY7VB0M1pWJcvef4iqwZoC6Pw2CoU3BodVDqMaZ3hxPY=
deploy:
  provider: pypi
  user: "InbarRose"
  password:
    secure: N8UpHF0GtRdgDHpK6k5rnGWQFtzNBvj6gd2NjJXGo5DekEdMRBOIry5NbuYHj+TZ6q3yjWAaNXTtPTmv1O+x2pEt4bgLAxym6VkmY0ZKc1NRgr5FtmTsVh/CBb73LoHABYLaKtBBQg/4vsYesut2i5icUgOi3TTTZ4Ni6zlRdiv0WyG3q2vTlFD8SIwQec4XXJyOuvWQy38hrvZ26f0lbGL65CJ+CY5SBf8CU2uoPJqySTHk6K3vIjrPGwh0JYQVVpWZGy+/hIsXLI7TAgbno4a0MFDZYuq2mfqE0Yyy0JxNoHFXgjuTtUQytRMeOCNLHcg0m6jtv0brWwajkna/34MKVjQezX+t7K8BobdXyP//LHfH5MjDAY6mDPoiIhxPwPWkO13rO22irj9kJRVGJceT2+oMpK5wjZqv2G4oNAs2yNNSa+flnAGVyoKCAj9y9VfQF460wg1CYKvYop35R+OK6e1V3ECVSrOxeJ3YsArpqk4f7LWhrmAk+fmZlEYqNyRzSl6/oyRNha+N24t90qQAAbBZ2z/ubnbib6z0vDJ9Eo2AQLn7g3y3x7DdbfVaTmA+6tZjGXJyMEhY8Oe813ft7opmF+8Zx/Mmv5Uo67rkQh0Banb3wzrvVj2K8esY4WhrJnnXrPI2cAZb/oAp6T33I9YCIcVWXgJUTlGvSxc=
