language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- pytest
notifications:
  slack:
    secure: e2PmfHLfjsJFXzDcBCImkjbW0NqcrDAdHRcXwvrretIzasW1ZnC6Bto1kT0mhVEiPWzyBcUdHqji6zG5D3x/Cs9HVrwdkCfSjawC7H7eZBBdYV5w9JFJGLkZTumrT6xhfpEsndRe/oX6VKYGmfDBu8NxfL4hzNRNQtDQkh4a1ruNg5QZTz2xyq37pcb4rnGtp4WNBNyo48z76AkCW5sKxitoa2zhbqtYbqbAzpOP7Qf2TAXYh+AkIlim9IC63+GC96WVZyl65JqnJORRiGnGmM75E59UZ58wiGiDgWXqteA+6nLTC6+P6P50cVLnObXfda+M3URJ+aRwTkhkPm7OLrVOUncILZm0RSrYLC2ZN1QW8XOwCKwSmdOFKfwvh2wdgffCtD2gVDGLIUr74siEqMAER/K9L4Z3S0/SqT56B+fvazRJT9L6ClWz6TVpGuDZvuX2c+fEGJm7tc5MqopWoiBsAPzuj21eq9XcFmj6nRc/PKC5wCgWncQaY0pA4rSjTYfWMse+ZeFWq9G7NO/tR6nCDUhx7ks2AhiJrXX8ce0ZQ8a51CU9gbVhTWuqZ6zwL7KGaQirqvoBW9q2xu98TVOJ6bIx4mVk9fZEcDk1z7uwtaOmK8lDgpiQASAMYW9JY7VB0M1pWJcvef4iqwZoC6Pw2CoU3BodVDqMaZ3hxPY=
deploy:
  provider: pypi
  user: InbarRose
  password:
    secure: gv3+6a0fzmGpNnC5Nqv+vXC+fBmXtGt+GZxx5cawugawTYO6CPs4uEQqlF+XgT7OmtGpjw18ZAKM4yQ/TkKz+wuhufyWo3LU0HkZtURNd3fTmr+1wF4oeBLRn7ZvVE77bTld/u9qCGYBvCd+SMqWmpcacGfyXegzhsUF9qr4mJSzQ2H7Z9ky4F6q/EoM3xurJOXEiCMqU6Qi0x37A6dyMYOPO7eZdWQF9V1NCGomP9bvNSAmFitltwp8CRbyDNf7RAzrXvVzd/88GpWWK235u1sOrywQ3FF62v6Lz0zn2InfIdqc2NBydq9kZu6S8yOqNYDDwXJzfwYqumogrWaxClpEK9PF2jKZF1Y7/b/GT4s/XclYUa5XCNrYnXFJVmZI/vfGZ8bWR9NSplpwLk09rqdbUmfv9byghSPpWPNIrvcRbf53JvWr77t7wo+alyIj5U/Wt3G5c30J03KB6kbryme9RNerfzfVLVEJ2NzNs6NAw+UjymTbF3T58Tgvn8G2YYMUcKLGqKmkBRJMDZdMkFSI03ZL0KvYVp1hD+iEq/kpCHivi8cmLQlezuGpcFx7z6VI1fIwXzm/yM/q7Ygohq5IL75gB+RRiN1mTJKG+F9biRzKgoin84hYMtfYr9SkQcjQIfRRUZjz45foCjbkB0Mg1G1TiqOIW61ZeyI3ebQ=
